import type { Metadata } from 'next';
import { HelpCircle, MessageSquareText } from 'lucide-react';
import { PageHero } from '@/components/layout/PageHero';
import { FaqAccordion } from '@/components/interactive/FaqAccordion';
import { ContactForm } from '@/components/forms/ContactForm';
import { SectionTitle } from '@/components/ui/SectionTitle';
import { faqs } from '@/lib/data/faqs';

export const metadata:Metadata={title:'پرسش‌های متداول',description:'پاسخ به پرسش‌های متداول حقوقی و نحوه دریافت خدمات از خانه وکلا.'};
export default function FaqPage(){const schema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))};return <><PageHero eyebrow="پرسش و پاسخ" current="سؤالات متداول" title={<>پاسخ کوتاه برای<br/><span className="gold-text">پرسش‌های مهم شما</span></>} description="موضوع موردنظر را انتخاب کنید. پاسخ‌ها عمومی‌اند و برای تصمیم نهایی، شرایط و مدارک هر پرونده باید جداگانه بررسی شود."/><section className="section-space"><div className="container-shell grid gap-12 lg:grid-cols-[320px_1fr]"><aside><div className="sticky top-28 rounded-3xl bg-navy-900 p-7 text-white"><HelpCircle className="text-gold-500" size={30}/><h2 className="mt-5 text-xl font-black">پاسخ خود را پیدا نکردید؟</h2><p className="mt-3 text-xs leading-7 text-white/55">سؤال خود را ارسال کنید یا برای بررسی اختصاصی، زمان مشاوره بگیرید.</p><a href="#ask" className="mt-5 inline-flex items-center gap-2 text-sm font-black text-gold-400"><MessageSquareText size={17}/>پرسیدن سؤال</a></div></aside><div><FaqAccordion items={faqs} withFilters/></div></div></section><section id="ask" className="section-space bg-white"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle eyebrow="سؤال شما" title={<>پرسش خود را<br/><span className="text-gold-500">برای ما بنویسید</span></>} description="برای حفظ حریم خصوصی، نام اشخاص، شماره پرونده یا اطلاعات بسیار حساس را در فرم عمومی وارد نکنید."/><div className="rounded-3xl border border-gray-100 bg-gray-50 p-6 sm:p-8"><ContactForm kind="question"/></div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
