import type { Metadata } from 'next';
import Image from 'next/image';
import { Award, BadgeCheck, BookOpen, Eye, HeartHandshake, Scale, ShieldCheck, Sparkles } from 'lucide-react';
import { PageHero } from '@/components/layout/PageHero';
import { SectionTitle } from '@/components/ui/SectionTitle';
import { Button } from '@/components/ui/Button';
import { Reveal } from '@/components/animation/Reveal';
import { SITE } from '@/lib/constants';

export const metadata:Metadata={title:'درباره مؤسسه',description:'داستان، ارزش‌ها و رویکرد مؤسسه حقوقی خانه وکیل در قزوین.'};
const timeline=[['۱۳۸۸','آغاز فعالیت حرفه‌ای','شروع مسیر وکالت با تمرکز بر دعاوی حقوقی و قراردادها.'],['۱۳۹۳','گسترش حوزه خدمات','همکاری با متخصصان خانواده، کیفری و امور ثبتی.'],['۱۳۹۸','مشاوره کسب‌وکارها','توسعه خدمات قرارداد و مشاوره مستمر حقوقی شرکت‌ها.'],['۱۴۰۵','خانه وکیل امروز','تمرکز بر تجربه شفاف، دسترسی بهتر و فرایندهای منظم.']];
const values=[[Scale,'عدالت و استقلال','تحلیل پرونده بدون پیش‌داوری و ارائه نظر حرفه‌ای مستقل.'],[Eye,'شفافیت','توضیح روشن هزینه، زمان، احتمال‌ها و ریسک پیش از هر اقدام.'],[ShieldCheck,'محرمانگی','حفاظت مسئولانه از اطلاعات، اسناد و اعتماد موکل.'],[HeartHandshake,'احترام','شنیدن دقیق و رفتار محترمانه در تمام نقاط تماس.'],[BookOpen,'یادگیری مستمر','به‌روزرسانی دانش با قوانین، رویه و تحلیل‌های جدید.'],[Sparkles,'کیفیت','دقت در نگارش، مستندسازی و پیگیری تا آخرین مرحله.']];

export default function AboutPage(){return <>
<PageHero eyebrow="درباره ما" current="درباره مؤسسه" title={<>یک خانه امن برای<br/><span className="gold-text">تصمیم‌های حقوقی</span></>} description="خانه وکیل برای ساده‌کردن قانون تأسیس شده است؛ نه با وعده‌های بزرگ، بلکه با تحلیل دقیق، گفت‌وگوی صادقانه و پیگیری حرفه‌ای."/>
<section className="section-space"><div className="container-shell grid items-center gap-14 lg:grid-cols-2"><Reveal direction="right"><div className="relative aspect-[5/4] overflow-hidden rounded-[2rem]"><Image src="/images/hero/legal-office.jpg" alt="فضای مؤسسه حقوقی خانه وکیل" fill className="object-cover" sizes="(max-width:1024px) 100vw,50vw"/><div className="absolute inset-0 bg-gradient-to-t from-navy-950/60 to-transparent"/><span className="absolute bottom-5 right-5 rounded-xl bg-white/90 px-4 py-2 text-xs font-bold text-navy-900">قزوین · خیابان خیام جنوبی</span></div></Reveal><Reveal direction="left"><SectionTitle eyebrow="داستان ما" title={<>قانون، وقتی ارزشمند است که<br/><span className="text-gold-500">به تصمیم درست کمک کند</span></>}/><p className="mt-6 leading-[2.1] text-gray-600">فعالیت حرفه‌ای مؤسسه با این باور شکل گرفت که موکل باید پیش از ورود به هر مسیر حقوقی، تصویر روشنی از انتخاب‌ها و پیامدها داشته باشد. ما زمان کافی برای شنیدن مسئله و مطالعه مدارک اختصاص می‌دهیم.</p><p className="mt-4 leading-[2.1] text-gray-600">امروز، خانه وکیل با شبکه‌ای از تخصص‌های مکمل تلاش می‌کند تجربه دریافت خدمات حقوقی را منظم‌تر، انسانی‌تر و قابل پیگیری‌تر کند.</p><Button href="/consultation/" className="mt-8">شروع یک گفت‌وگو</Button></Reveal></div></section>
<section className="section-space bg-white"><div className="container-shell"><SectionTitle eyebrow="مسیر رشد" title="از تجربه فردی تا یک تیم حقوقی" align="center"/><div className="relative mt-14 grid gap-5 lg:grid-cols-4"><i className="absolute right-[8%] top-7 hidden w-[84%] border-t border-dashed border-gold-500/40 lg:block"/>{timeline.map(([year,title,text],index)=><Reveal key={year} delay={index*.08}><article className="relative rounded-3xl border border-gray-100 bg-white p-6 shadow-sm"><span className="relative z-10 inline-grid h-14 min-w-14 place-items-center rounded-2xl bg-navy-900 px-3 font-black text-gold-400">{year}</span><h3 className="mt-5 font-black text-navy-900">{title}</h3><p className="mt-2 text-xs leading-7 text-gray-500">{text}</p></article></Reveal>)}</div></div></section>
<section className="section-space"><div className="container-shell"><SectionTitle eyebrow="اصول حرفه‌ای" title={<>ارزش‌هایی که هر روز<br/><span className="text-gold-500">با آن‌ها سنجیده می‌شویم</span></>} align="center"/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{values.map(([Icon,title,text],i)=>{const I=Icon as typeof Scale;return <Reveal key={title as string} delay={i*.05}><article className="rounded-3xl border border-gray-100 bg-white p-7"><I className="text-gold-500" size={27}/><h3 className="mt-5 font-black text-navy-900">{title as string}</h3><p className="mt-2 text-xs leading-7 text-gray-500">{text as string}</p></article></Reveal>})}</div></div></section>
<section className="section-space bg-navy-950 text-white"><div className="container-shell grid items-center gap-14 lg:grid-cols-[.75fr_1.25fr]"><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src="/images/lawyers/manager-portrait.jpg" alt="تصویر پیشنهادی علی کشاورز نجفی" fill className="object-cover object-top"/><span className="absolute bottom-4 right-4 rounded-lg bg-navy-950/80 px-3 py-2 text-[9px] text-white/60">تصویر پیشنهادی — نیازمند تأیید</span></div><div><span className="eyebrow">مدیریت مؤسسه</span><h2 className="mt-4 text-4xl font-black">{SITE.manager}</h2><p className="mt-3 text-gold-400">{SITE.managerTitle}</p><p className="mt-7 leading-[2] text-white/60">رویکرد مدیریتی مؤسسه بر کیفیت بررسی، شفافیت ارتباط و پاسخ‌گویی بنا شده است. پذیرش هر پرونده پس از ارزیابی اولیه و با توافق روشن درباره حدود خدمات انجام می‌شود.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['شماره پروانه: '+SITE.licenseNumber,'عضو کانون وکلای قزوین','[مدرک و گرایش تحصیلی]','۱۴+ سال تجربه حرفه‌ای'].map(item=><span key={item} className="flex items-center gap-2 text-sm text-white/70"><BadgeCheck size={17} className="text-gold-500"/>{item}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><Button href="/lawyers/ali-keshavarz-najafi/" variant="light">مشاهده پروفایل</Button><Button href="/consultation/">رزرو مشاوره</Button></div></div></div></section>
<section className="section-space bg-white"><div className="container-shell"><SectionTitle eyebrow="مجوزها و گواهی‌ها" title="اطلاعات قانونی، شفاف و قابل بررسی"/><div className="mt-10 grid gap-4 md:grid-cols-3">{['پروانه وکالت پایه یک','گواهی عضویت کانون','[گواهینامه تخصصی]'].map((item,i)=><div key={item} className="flex items-center gap-4 rounded-2xl border border-dashed border-gray-200 p-5"><span className="grid size-12 place-items-center rounded-xl bg-gold-500/10 text-gold-500">{i<2?<Award/>:<BadgeCheck/>}</span><div><b className="text-sm text-navy-900">{item}</b><small className="mt-1 block text-[10px] text-gray-400">[تصویر و شماره مدرک]</small></div></div>)}</div></div></section>
</>}
