import type { Metadata } from 'next';
import { Clock3, Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { PageHero } from '@/components/layout/PageHero';
import { SectionTitle } from '@/components/ui/SectionTitle';
import { ContactForm } from '@/components/forms/ContactForm';
import { SITE } from '@/lib/constants';

export const metadata:Metadata={title:'تماس با ما',description:'نشانی، تلفن، ساعات کار و فرم تماس خانه وکلا در قزوین.'};
export default function ContactPage(){const cards=[[MapPin,'نشانی خانه وکلا',SITE.address,'/contact/'],[Phone,'تلفن مستقیم',SITE.phone,SITE.phoneHref],[MessageCircle,'واتساپ',SITE.mobile,SITE.whatsappHref],[Mail,'پست الکترونیک',SITE.email,`mailto:${SITE.email}`]];return <><PageHero eyebrow="در ارتباط باشیم" current="تماس با ما" title={<>نزدیک و پاسخ‌گو،<br/><span className="gold-text">وقتی به ما نیاز دارید</span></>} description="برای بازدید از فضا، عضویت، رزرو اتاق یا هماهنگی رویداد از راه‌های زیر با ما در تماس باشید."/><section className="section-space"><div className="container-shell"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([Icon,title,value,href])=>{const I=Icon as typeof MapPin;return <a key={title as string} href={href as string} className="group rounded-3xl border border-gray-100 bg-white p-6 transition hover:-translate-y-1 hover:border-gold-500 hover:shadow-soft"><span className="grid size-12 place-items-center rounded-2xl bg-navy-900 text-gold-500 transition group-hover:bg-gold-500 group-hover:text-navy-950"><I size={21}/></span><h2 className="mt-5 text-sm font-black text-navy-900">{title as string}</h2><p className="mt-2 text-xs leading-6 text-gray-500">{value as string}</p></a>})}</div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-gold-500/10 p-4 text-xs text-navy-900"><Clock3 className="text-gold-500" size={18}/><b>ساعات پاسخ‌گویی:</b> {SITE.workHours}</div></div></section><section className="section-space bg-white"><div className="container-shell grid gap-12 lg:grid-cols-2"><div><SectionTitle eyebrow="ارسال پیام" title={<>موضوع خود را<br/><span className="text-gold-500">کوتاه برای ما بنویسید</span></>} description="این فرم برای ارتباط اولیه است. برای رزرو اتاق از صفحه اتاق‌های مشاوره و برای عضویت از فرم عضویت استفاده کنید."/><div className="mt-8"><ContactForm/></div></div><div><SectionTitle eyebrow="موقعیت" title="خیابان خیام جنوبی، قزوین"/><div className="mt-8 h-[460px] overflow-hidden rounded-[2rem] border border-gray-100 bg-gray-100"><iframe title="نقشه موقعیت خانه وکلا در قزوین" src="https://www.openstreetmap.org/export/embed.html?bbox=50.0000%2C36.2400%2C50.0300%2C36.2900&amp;layer=mapnik" className="h-full w-full border-0" loading="lazy"/></div><p className="mt-3 text-[10px] leading-6 text-gray-400">موقعیت نقشه تقریبی است و پس از دریافت نشانی و پلاک دقیق باید به‌روزرسانی شود.</p></div></div></section></>}
