import type { Metadata } from 'next';
import { CalendarDays, CheckCircle2, MessageSquareText, PhoneCall } from 'lucide-react';
import { PageHero } from '@/components/layout/PageHero';
import { ConsultationCards } from '@/components/consultation/ConsultationCards';
import { BookingWidget } from '@/components/consultation/BookingWidget';
import { SectionTitle } from '@/components/ui/SectionTitle';

export const metadata:Metadata={title:'رزرو مشاوره حقوقی',description:'رزرو آنلاین مشاوره حضوری، تلفنی یا آنلاین با مؤسسه حقوقی خانه وکیل.'};
const steps=[[MessageSquareText,'انتخاب نوع جلسه','شیوه مناسب را بر اساس نیاز و دسترسی خود انتخاب کنید.'],[CalendarDays,'تاریخ و ساعت','یکی از زمان‌های آزاد تقویم را رزرو اولیه کنید.'],[CheckCircle2,'ثبت اطلاعات','اطلاعات تماس و توضیح کوتاه موضوع را وارد کنید.'],[PhoneCall,'تأیید نهایی','همکاران ما برای تأیید و راهنمای ارسال مدارک تماس می‌گیرند.']];
export default function ConsultationPage(){return <><PageHero eyebrow="رزرو آنلاین" current="مشاوره" title={<>یک گفت‌وگوی دقیق،<br/><span className="gold-text">پیش از یک تصمیم مهم</span></>} description="نوع مشاوره و زمان مناسب را انتخاب کنید. ثبت فرم به معنی رزرو اولیه است و زمان جلسه پس از تماس مؤسسه قطعی می‌شود."/><section className="section-space"><div className="container-shell"><SectionTitle eyebrow="شیوه جلسه" title="چطور گفت‌وگو کنیم؟" align="center"/><div className="mt-12"><ConsultationCards/></div></div></section><section className="bg-white py-14"><div className="container-shell"><div className="grid gap-8 md:grid-cols-4">{steps.map(([Icon,title,text],index)=>{const I=Icon as typeof CalendarDays;return <div key={title as string} className="relative text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-navy-900 text-gold-500"><I size={23}/></span><span className="mt-4 block text-[9px] font-black text-gold-500">مرحله {index+1}</span><h3 className="mt-1 text-sm font-black text-navy-900">{title as string}</h3><p className="mt-2 text-[11px] leading-6 text-gray-500">{text as string}</p></div>})}</div></div></section><section id="booking" className="section-space bg-[#F0F1F4]"><div className="container-shell"><SectionTitle eyebrow="تقویم مشاوره" title={<>روز و ساعت مناسب را<br/><span className="text-gold-500">در تقویم انتخاب کنید</span></>} description="زمان‌ها به‌صورت نیم‌ساعته نمایش داده می‌شوند. جمعه‌ها، تعطیلات رسمی و ساعت استراحت قابل انتخاب نیستند."/><div className="mt-10"><BookingWidget/></div></div></section></>}
