import type { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { Award, BadgeCheck, BookOpen, CalendarDays, Clock3, GraduationCap, Mail, Phone, UserRound } from 'lucide-react';
import { lawyers, getLawyer } from '@/lib/data/lawyers';
import { SITE } from '@/lib/constants';
import { PageHero } from '@/components/layout/PageHero';
import { SectionTitle } from '@/components/ui/SectionTitle';
import { Button } from '@/components/ui/Button';
import { ArticleCard } from '@/components/cards/ArticleCard';
import { articles } from '@/lib/data/articles';

export function generateStaticParams(){return lawyers.map(lawyer=>({slug:lawyer.slug}))}
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const lawyer=getLawyer(params.slug);return lawyer?{title:lawyer.name,description:`پروفایل ${lawyer.name}، ${lawyer.role} در خانه وکلا.`}:{title:'پروفایل وکیل'}}
export default function LawyerProfile({params}:{params:{slug:string}}){const lawyer=getLawyer(params.slug);if(!lawyer)notFound();return <>
<PageHero eyebrow={lawyer.specialty} current={lawyer.name} title={<>{lawyer.name}<br/><span className="gold-text">{lawyer.role}</span></>} description="آشنایی با سوابق، حوزه‌های تمرکز و زمان‌های مشاوره."/>
<section className="section-space"><div className="container-shell grid gap-12 lg:grid-cols-[380px_1fr]"><aside><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem] bg-navy-900">{lawyer.image?<Image src={lawyer.image} alt={`تصویر پیشنهادی ${lawyer.name}`} fill className="object-cover object-top" sizes="380px"/>:<div className="legal-pattern absolute inset-0 grid place-items-center text-gold-500"><UserRound size={90} strokeWidth={.7}/></div>}{lawyer.placeholder&&<span className="absolute bottom-4 right-4 rounded-lg bg-navy-950/80 px-3 py-2 text-[9px] text-white/60">تصویر و اطلاعات در انتظار تکمیل</span>}</div><div className="mt-4 rounded-3xl border border-gray-100 bg-white p-6"><h3 className="font-black text-navy-900">راه ارتباط و رزرو</h3><a href={SITE.phoneHref} className="mt-4 flex items-center gap-3 text-sm text-gray-600"><Phone size={17} className="text-gold-500"/><span dir="ltr">{SITE.phone}</span></a><a href={`mailto:${SITE.email}`} className="mt-3 flex items-center gap-3 text-sm text-gray-600"><Mail size={17} className="text-gold-500"/>{SITE.email}</a><Button href="/consultation/" className="mt-5 w-full"><CalendarDays size={17}/>رزرو مشاوره</Button></div></aside><article><span className="eyebrow">معرفی حرفه‌ای</span><h2 className="mt-4 text-3xl font-black text-navy-900">درباره {lawyer.name}</h2><p className="mt-6 leading-[2.15] text-gray-600">{lawyer.bio}</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-gray-100 bg-white p-6"><GraduationCap className="text-gold-500"/><h3 className="mt-4 font-black text-navy-900">تحصیلات و عضویت‌ها</h3><ul className="mt-4 space-y-3">{lawyer.education.map(item=><li key={item} className="flex gap-2 text-xs text-gray-500"><BadgeCheck size={15} className="shrink-0 text-gold-500"/>{item}</li>)}</ul></div><div className="rounded-3xl border border-gray-100 bg-white p-6"><Award className="text-gold-500"/><h3 className="mt-4 font-black text-navy-900">حوزه‌های تمرکز</h3><div className="mt-4 flex flex-wrap gap-2">{lawyer.tags.map(tag=><span key={tag} className="rounded-lg bg-gold-500/10 px-3 py-2 text-xs font-bold text-navy-900">{tag}</span>)}</div></div></div><div className="mt-8 rounded-3xl bg-navy-900 p-7 text-white"><div className="flex items-center gap-3"><Clock3 className="text-gold-500"/><h3 className="font-black">زمان‌های پاسخ‌گویی</h3></div><p className="mt-4 text-sm text-white/60">{SITE.workHours} — صرفاً با هماهنگی قبلی</p></div></article></div></section>
<section className="section-space bg-white"><div className="container-shell"><SectionTitle eyebrow="یادداشت‌ها و مقالات" title="مطالب نوشته‌شده و منتخب"/><div className="mt-10 grid gap-5 md:grid-cols-3">{articles.slice(0,3).map((article,index)=><ArticleCard key={article.slug} article={article} index={index}/>)}</div></div></section>
</>}
